version: 2.1
orbs:
  node: circleci/node@4.5.0
  aws-cli: circleci/aws-cli@2.0
  sam: circleci/aws-sam-serverless@3.1.0
jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - sam/install:
          aws-access-key-id: AWS_ACCESS_ID
          aws-secret-access-key: AWS_SECRET_KEY
      - node/install:
          node-version: 14.15.1
          npm-version: 6.14.8
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Install aws cli
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            aws --version
            sam --version
      - run:
          name: Build API
          command: |
            npm run build
      - run:
          name: Deploy to API and Lambdas
          command: |
            sudo apt-get install zip
            mkdir nodejs
            cp -r node_modules nodejs
            zip -r ./cube-scramble-api-layer.zip nodejs/
            aws lambda publish-layer-version --layer-name cube-scramble-api-layer --description "Cube Scramble API node_modules" --zip-file fileb://cube-scramble-api-layer.zip --compatible-runtimes nodejs10.x nodejs12.x nodejs14.x
            LATEST_LAYER_VERSION=$(aws lambda list-layer-versions --layer-name cube-scramble-api-layer --region us-east-1 --query 'LayerVersions[0].LayerVersionArn')
            echo "Latest Layer Version: $LATEST_LAYER_VERSION"
            sam package --template-file template.yml --output-template-file packaged.yaml --s3-bucket cube-timer-lake --s3-prefix cloudformation-templates/cube-scramble-api --force-upload
            sam deploy --template-file packaged.yaml --stack-name cube-scramble-api --capabilities CAPABILITY_IAM --parameter-overrides CurrentNodeModulesLayerVersion=${LATEST_LAYER_VERSION}
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context:
            - AWS_CONTEXT
